# Site settings
title: ROCKTREFF
email: kontakt@rocktreff.de
description: ""
baseurl: ""
url: "http://www.rocktreff.de"
exclude: [ "styles" ]
plugins:
  - jekyll-minifier

default_locale: "de"

# collections
collections:
  bands:
    output: true
  presse:
    output: true


flickr:
  api_key: 'f2fedaf7f36bf5739b3eba547ab384b2'
  user_id: '80099500@N05'
  use_cache: true

jekyll-minifier:
  preserve_php: true
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_intertag_spaces: true
  remove_quotes: false
  compress_css: true
  compress_javascript: true
  simple_doctype: false
  remove_script_attributes: false
  remove_style_attributes: false
  remove_link_attributes: false
  remove_form_attributes: false
  remove_input_attributes: false
  remove_javascript_protocol: false
  remove_http_protocol: false
  remove_https_protocol: false
  preserve_line_breaks: false
  simple_boolean_attributes: false
  compress_js_templates: false

# Build settings
markdown: kramdown
permalink: pretty
