# Site settings
title: ROCKTREFF
email: kontakt@rocktreff.de
description: ""
baseurl: ""
url: "https://rocktreff.de"
exclude: []

default_locale: "de"

# collections
collections:
  bands:
    output: true
  presse:
    output: true


# Build settings
markdown: kramdown
permalink: pretty
