name: Build & Upload rocktreff.de

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

    - uses: actions/checkout@master

    - name: Build Site
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/app:Z" \
          -w /app \
          jekyll/builder:4.1.0 \
          /bin/bash -c "chmod -R 777 . && jekyll build -s source -d dist -c config.yml"

    - name: Minify Images
      run: |
        docker run --rm\
          -v "${{ github.workspace }}:/app:Z" \
          -w /app \
          jess/imagemin:latest \
          imagemin source/images --out-dir=dist/images

    - name: Compile CSS
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/app:Z" \
          -w /app \
          finalgene/lessc:latest \
          lessc source/styles/main.less dist/styles/main.css

    - name: PostCSS
      if: ${{ false }}
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/app:Z" \
          -w /app \
          deryabinsergey/postcss:latest \
          postcss --no-map -o dist/styles/main.css dist/styles/*.css

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
