name: Build & Upload rocktreff.de

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Build Site
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/app:Z" \
          -w /app \
          jekyll/builder:4.1.0 \
          /bin/bash -c "chmod -R 777 . && jekyll build -s source -d dist -p plugins -c config.yml"

    - name: Minify Images
      run: |
        docker run --rm\
          -v "${{ github.workspace }}:/app:Z" \
          -w /app \
          jess/imagemin:latest \
          imagemin source/images --out-dir=dist/images

    - name: Compile CSS
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/app:Z" \
          -w /app \
          finalgene/lessc:latest \
          lessc source/styles/main.less dist/styles/main.css

    - name: PostCSS
      if: ${{ false }}
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/app:Z" \
          -w /app \
          deryabinsergey/postcss:latest \
          postcss --no-map -o dist/styles/main.css dist/styles/*.css

    - name: Upload
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'
        SOURCE_DIR: 'dist'
